controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

book_search:
  path: /book/search
  controller: App\Controller\BookSearchController::search
  methods: GET
